require 'rake'
task :default=>["tagfile/tagfile.so","taglib/TagLib.so"]

file "tagfile/tagfile.so" => ["tagfile/Rakefile.rb"] do |t|
	system %(cd tagfile && rake)
end

file "taglib/TagLib.so" => ["taglib/Rakefile.rb"] do |t|
	system %(cd taglib && rake)
end
